# Docker compose of the project
#
# Change {project} to your project's name and {client} for the client's name
# Comment or remove entries not used for your project
# You may remove this comments
#

version: "3.7"
services:

  requirements:
    container_name: giscube_giscube-admin_requirements
    build:
      context: .
      dockerfile: docker/django/ubuntu-18.04/Dockerfile
      args:
        - EXTRA_REQUIREMENTS=devel
    image: giscube_giscube-admin_requirements
    entrypoint: /bin/bash -c "chown -v www-data:www-data /app_data"
    command: []
    volumes:
      - app_data:/app_data

  db:
    image: mdillon/postgis:11
    env_file:
     - app.env
    volumes:
      - .:/app
      - pg_data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    networks:
      default:
        aliases:
          - giscube-admin-db.giscube

  django:
    container_name: giscube_giscube-admin_django
    depends_on:
      - requirements
      - db
    image: giscube_giscube-admin_requirements
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/scripts/wait-for-it.sh", "db:5432", "--", "/bin/bash", "/app/docker/django/runserver.sh"]
    volumes:
      - .:/app:cached
      - app_data:/app_data
      - ../giscube-admin-ee-plugins:/giscube-admin-ee-plugins
    environment:
      - PYTHONPATH=${PYTONPATH}:/giscube-admin-ee-plugins
      - GISCUBE_PLUGINS_PATH=/giscube-admin-ee-plugins
      - GISCUBE_PLUGINS=geoportal_search_autoupdate

    networks:
      default:
        aliases:
          - giscube-admin.giscube

  uwsgi:
    container_name: giscube_giscube-admin_uwsgi
    depends_on:
      - requirements
      - db
    image: giscube_giscube-admin_requirements
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/scripts/wait-for-it.sh", "db:5432", "--", "/bin/bash", "/app/docker-custom/uwsgi/runserver.sh"]
    volumes:
      - .:/app:cached
      - app_data:/app_data
      - ../giscube-admin-ee-plugins:/giscube-admin-ee-plugins
      - static:/static
    environment:
      - DEBUG=False
      - STATIC_ROOT=/static
      - PYTHONPATH=${PYTONPATH}:/giscube-admin-ee-plugins
      - GISCUBE_PLUGINS_PATH=/giscube-admin-ee-plugins
      - GISCUBE_PLUGINS=geoportal_search_autoupdate
    ports:
    - "8002:8000"

    # networks:
    #   default:
    #     aliases:
    #       - giscube-admin.giscube

  celery:
    depends_on:
      - requirements
      - redis
      - db
    image: giscube_giscube-admin_requirements
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/scripts/wait-for-it.sh", "db:5432", "--",  "/bin/bash", "/app/docker-custom/django/celery_devel.sh"]
    volumes:
      - .:/app:cached
      - app_data:/app_data

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  nginx:
    build:
      context: docker-custom/nginx/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./docker-custom/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-custom/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static

  qgisserver:
    build:
      context: docker-custom/qgisserver/
      dockerfile: Dockerfile
    image: giscube_admin_qgisserver
    volumes:
      - app_data:/app_data

  imageserver:
    build:
      context: docker-custom/imageserver/
      dockerfile: Dockerfile
    environment:
        - MS_DEBUGLEVEL=5
    volumes:
      - app_data:/app_data

volumes:
  app_data:
  pg_data:
  redis_data:
  static:

networks:
  default:
    external:
      name: giscube
